### ISSUE TITLE
UID, GID, and UMASK arguments for container

### ISSUE THREAD

**Issue by tonyhardcode** [marcopeocchi/yt-dlp-web-ui#112]
Is it possible to add these arguments to the container so downloaded files can be created under the user, group and umask specified? Would help with permission issues on the host.

**Comment by marcopeocchi** [comment]
For the files being created by a certain user, pass the `--user $UID:$GID ` flag to docker.

In order to find the correct UID-GID run these commands:

```sh
# UID
id -u your-user
# GID
id -g your user
```
then 
`docker run -d --name ... --user UID:GID`

Regarding the umask, this variable is up to yt-dlp itself. It could be added to the backend, i'll work on this.

**Comment by TheRealGramdalf** [comment]
For docker compose you can use the service-level element `user:`

```yml
services:
  ytdlp-ui:
    user: $UID:$GID
    image: ...
```
